### ISSUE TITLE
flexible docking failed for example

### ISSUE THREAD

**Issue by liuyujie714** [ccsb-scripps/AutoDock-Vina#19] opened 2021-08-05 10:47 UTC
Your example for flexibledocking is failed.
```
(base) liuyujie714@ubuntu:~/Documents/flexible_docking/solution$ ./vina_1.2.1_linux_x86_64  --receptor 1fpu_receptor_rigid.pdbqt --flex 1fpu_receptor_flex.pdbqt \
>        --ligand 1iep_ligand.pdbqt --config 1fpu_receptor_rigid_vina_box.txt \
>        --exhaustiveness 32 --out 1fpu_ligand_flex_vina_out.pdbqt
AutoDock Vina v1.2.1
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli  #
# AutoDock Vina 1.2.0: New Docking Methods, Expanded Force      #
# Field, and Python Bindings, J. Chem. Inf. Model. (2021)       #
# DOI 10.1021/acs.jcim.1c00203                                  #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, J. Comp. Chem. (2010)                         #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see https://github.com/ccsb-scripps/AutoDock-Vina for  #
# more information.                                             #
#################################################################

Scoring function : vina
Rigid receptor: 1fpu_receptor_rigid.pdbqt
Flex receptor: 1fpu_receptor_flex.pdbqt
Ligand: 1iep_ligand.pdbqt
Center: X 15.19 Y 53.903 Z 16.917
Size: X 20 Y 20 Z 20
Grid space: 0.375
Exhaustiveness: 32
CPU: 0
Verbosity: 1



An unknown error occurred. 

Please report bugs through the Issue Tracker on GitHub 
(https://github.com/ccsb-scripps/AutoDock-Vina/issues)., so
that this problem can be resolved. The reproducibility of the
error may be vital, so please remember to include the following in
your problem report:
* the EXACT error message,
* your version of the program,
* the type of computer system you are running it on,
* all command line options,
* configuration file (if used),
* ligand file as PDBQT,
* receptor file as PDBQT,
* flexible side chains file as PDBQT (if used),
* output file as PDBQT (if any),
* input (if possible),
* random seed the program used (this is printed when the program starts).

Thank you!
```

**Comment by jeeberhardt** [comment] 2021-08-06 07:42
Hi liuyujie714,

The ligand file `1iep_ligand.pdbqt` is not in the `solution` directory. If you replace `--ligand 1iep_ligand.pdbqt` by `--ligand ../data/1iep_ligand.pdbqt` it works.

Best,

**Comment by liuyujie714** [comment] 2021-08-06 07:49
> Hi liuyujie714,
> 
> The ligand file `1iep_ligand.pdbqt` is not in the `solution` directory. If you replace `--ligand 1iep_ligand.pdbqt` by `--ligand ../data/1iep_ligand.pdbqt` it works.
> 
> Best,

okay! Thanks!
I think this error can be reported by program such " xxx file I/O error or can not found" may be better for user debug.

Best!

**Comment by jeeberhardt** [comment] 2021-08-09 08:32
Hi liuyujie714,

Thanks for your feedback, much appreciated! We actually realized there was indeed a small regression in terms of error messages compared to version 1.1.2. This is going to be fixed in the next version of AutoDock-Vina.

Best,

**Comment by liuyujie714** [comment] 2021-08-09 08:37
Yes, thanks!
In addtion, can you support python binding for windows platform? I have tested it is not work for windows system, although I have compiled windows Autodock vina 1.2.1 by visual studio 2019.

Many thanks,
Yujie

**Comment by jeeberhardt** [comment] 2021-08-09 09:55
Hi Yujie,

The Windows platform is not really our priority right now, due to the fact we are not really familiar with that platform anymore... (and also sadly lack of time).

Would you mind if you could share how you compiled AutoDock-Vina using visual studio? I could be just a a link or something else. This is something we could definitely add to the documentation for our Windows users. Thanks!

Best,
Jerome.

**Closed** 2021-08-17 12:51 UTC
